/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginForm;

import utils.RequestHandler;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.JSONException;
import org.json.JSONObject;
import org.mindrot.jbcrypt.BCrypt;

public class ChangePasswordForm extends javax.swing.JFrame {

    private RecoveryForm rec;
    private final RequestHandler handler = new RequestHandler();
    private String sentCode, requestedEmail;
    
    public ChangePasswordForm() {
        initComponents();
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkCodeLabel = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        confPass = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        checkButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Recovery Code");

        code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        confirm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/confirm.png"))); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("New Password");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Repeat Password");

        checkCodeLabel.setVisible(false);
        checkCodeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/wrong.png"))); // NOI18N

        newPass.setEnabled(false);
        newPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        confPass.setEnabled(false);
        confPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/back_button.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        checkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/checkButton.png"))); // NOI18N
        checkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addComponent(confirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confPass, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(checkButton)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(confirm)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        JSONObject record = null;

        try {
            String responseText = handler.RetrieveCredentials(requestedEmail, "angajati");
            record = new JSONObject(responseText);
            
            if (newPass.isEnabled()) {
                if (!String.valueOf(newPass.getPassword()).isEmpty()) {
                    if (String.valueOf(newPass.getPassword()).equals(String.valueOf(confPass.getPassword()))) {
                        handler.AddAccount(record.getString("nume"), record.getString("prenume"), record.getString("rol"),
                                requestedEmail, String.valueOf(newPass.getPassword()), record.getString("telefon"), record.getString("idangajat"));
                        handler.DeleteCode(requestedEmail);

                        JLabel label = new JLabel("Successfully changed passwords!");
                        label.setFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 18));
                        JOptionPane.showMessageDialog(null, label, "New Password confirmed", JOptionPane.INFORMATION_MESSAGE);

                        reinitialize();

                    } else {
                        errorWindow("Passwords don't match!");
                    }
                } else {
                    errorWindow("Password cannot be empty!");
                }
            } else {
                errorWindow("Code not validated yet!");
            }
            
            

        } catch (IOException | JSONException ex) {
        }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        reinitialize();
    }//GEN-LAST:event_backButtonActionPerformed

    private void checkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkButtonMouseClicked
        if (BCrypt.checkpw(code.getText(), sentCode)) {
            newPass.setEnabled(true);
            confPass.setEnabled(true);
            checkCodeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/ok.png")));
            checkCodeLabel.setVisible(true);
        } else {
            checkCodeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/wrong.png")));
            checkCodeLabel.setVisible(true);
        }
    }//GEN-LAST:event_checkButtonMouseClicked

    public void setEmailAndCode(String email, String cod){
        sentCode = cod;
        requestedEmail = email;
    }
    
    private void reinitialize(){
        code.setText("");
        newPass.setText("");
        newPass.setEnabled(false);
        confPass.setText("");
        confPass.setEnabled(false);
        checkCodeLabel.setVisible(false);
        setEmailAndCode(null, null);
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        rec.setVisible(true);
    }
    private void errorWindow(String message){
        JLabel label = new JLabel(message);
        label.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 18));
        JOptionPane.showMessageDialog(null, label, "Confirmation error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void setFrame(RecoveryForm form){
        this.rec = form;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangePasswordForm form = new ChangePasswordForm();
                form.setVisible(true);
                form.setEmailAndCode("mail@yahoo.com", "code");
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel checkButton;
    private javax.swing.JLabel checkCodeLabel;
    private javax.swing.JTextField code;
    private javax.swing.JPasswordField confPass;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField newPass;
    // End of variables declaration//GEN-END:variables
}
