/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainFrame;

import utils.RequestHandler;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.JSONException;

/**
 *
 * @author Cristi
 */
public class CreditScoreForm extends javax.swing.JFrame {

    private LoanApplicationForm applicationForm;
    private final RequestHandler handler = new RequestHandler();
    private double finalScore = 69.24;
    private int employeeLevel;
    
    public CreditScoreForm() {
        this.setUndecorated(true);
        initComponents();
        this.setScore(String.valueOf(finalScore));
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        risk = new javax.swing.JLabel();
        grantLoan = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        risk.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        risk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        risk.setText("label");

        grantLoan.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        grantLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/grant.png"))); // NOI18N
        grantLoan.setText("Grant Loan");
        grantLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grantLoanActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/back_button.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        score.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText("*score*");

        label.setBackground(new java.awt.Color(236, 234, 0));
        label.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Final Score:");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addComponent(grantLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(228, 228, 228)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(risk, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(219, 219, 219)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(risk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(label)
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(score)
                .addGap(104, 104, 104)
                .addComponent(grantLoan)
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grantLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grantLoanActionPerformed
       
        switch (employeeLevel) {
            case 1:
                if (applicationForm.getLoanValue() > 1000) {
                    errorWindow("You don't have the permission to grant loans exceeding 1000 euros!");
                } else {
                    addCredit();
                }
                break;
            case 2:
                if (applicationForm.getLoanValue() > 2500) {
                    errorWindow("You don't have the permission to grant loans exceeding 2500 euros!");
                } else {
                    addCredit();
                }
                break;
            default:
                addCredit();
                break;
        }
        
    }//GEN-LAST:event_grantLoanActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        applicationForm.setEnabled(true);
    }//GEN-LAST:event_backMouseClicked
    
    public void setScore(String Score){
        finalScore = Double.parseDouble(Score);
        if (finalScore > 100) finalScore = 100;
        
        score.setText(String.valueOf(finalScore));
        backgroundColor();
    }    
    
    private void backgroundColor(){
        if (finalScore < 50) {
            panel.setBackground(Color.BLACK);
            risk.setForeground(Color.WHITE);
            label.setForeground(Color.WHITE);
            score.setForeground(Color.WHITE);
            risk.setText("Massive risk");
            
        } else if (finalScore >= 50 && finalScore < 60) {
            panel.setBackground(new Color(228, 0, 60));
            risk.setText("Very high risk");
            
        } else if (finalScore >= 60 && finalScore < 70) {
            panel.setBackground(new Color(255, 51, 0));
            risk.setText("Considerable risk");
            
        } else if (finalScore >= 70 && finalScore < 80) {
            panel.setBackground(new Color(235, 235, 0));
            risk.setText("Moderate risk");
            
        } else if (finalScore >= 80 && finalScore < 90) {
            panel.setBackground(new Color(51, 255, 51));
            risk.setText("Low risk");
            
        } else if (finalScore >= 90) {
            panel.setBackground(new Color(51, 204, 0));
            risk.setText("Negligable risk");
        }
            
    }
     
    private void errorWindow(String message){
        JLabel windowLabel = new JLabel(message);
        windowLabel.setFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 17));
        JOptionPane.showMessageDialog(null, windowLabel, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void confirmationWindow(String message){
        JLabel windowLabel = new JLabel(message);
        windowLabel.setFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 17));
        JOptionPane.showMessageDialog(null, windowLabel, "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void addCredit() {
        
        double monthlyRate = applicationForm.getLoanValue() / applicationForm.getLoanDuration();
        
        int reply = JOptionPane.showConfirmDialog(null, "Grant Loan?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                handler.AddCredit(applicationForm.getLoanValue(), monthlyRate, 
                        applicationForm.getLoanDuration(), applicationForm.getEmployeeEmail(), applicationForm.getClientEmail());               
            } catch (IOException | JSONException ex) {
            }
            confirmationWindow("Loan granted successfully!");
            this.setVisible(false);
            this.setLocationRelativeTo(null);
            applicationForm.reinitialize();
        }
    }
        
    
    public void setNivelAngajat(int lvl){
        employeeLevel = lvl;
    }
    
    public void setClass(LoanApplicationForm form){
        this.applicationForm = form;
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditScoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreditScoreForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton grantLoan;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel risk;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
