package mainFrame;

import utils.RequestHandler;
import java.awt.Font;
import loginForm.Login;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.json.JSONException;
import org.json.JSONObject;
/**
 *
 * @author Cristi
 */

public class Frame extends javax.swing.JFrame{

    private String employeeEmail;
    private String data;
    private int nivel;
    private String[] iban;
    private Blob[] fisiereBlob;
    private byte[][] fisiereBytes;  
    private ArrayList<JSONObject> entriesJSON;
    private DefaultTableModel model;
    private final DefaultTableCellRenderer CellRenderer = new DefaultTableCellRenderer();
    
    private Login login;
    private Transactions trans;
    private AddClientForm ClientForm;
    private LoanApplicationForm loanForm;
    private final RequestHandler handler = new RequestHandler();
    
    public Frame() throws IOException, JSONException{
        initComponents();
        initTable();
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        Transactions = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelClienti = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Nume = new javax.swing.JLabel();
        addClient = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        accessLoanForm = new javax.swing.JLabel();
        attribute = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/exit.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Transactions.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Transactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/transactions.png"))); // NOI18N
        Transactions.setText("Transactions");
        Transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsActionPerformed(evt);
            }
        });

        tabelClienti.setBorder(new javax.swing.border.MatteBorder(null));
        tabelClienti.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tabelClienti.getTableHeader().setFont(new Font("Franklin Gothic Book", 0, 17));
        tabelClienti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Last Name", "Surname", "Email", "Phone number", "Balance", "Active credit", "IBAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelClienti.setGridColor(new java.awt.Color(255, 255, 255));
        tabelClienti.setRowHeight(20);
        tabelClienti.getColumnModel().getColumn(2).setPreferredWidth(150);
        tabelClienti.getColumnModel().getColumn(3).setPreferredWidth(55);
        tabelClienti.getColumnModel().getColumn(4).setPreferredWidth(50);
        tabelClienti.getColumnModel().getColumn(5).setPreferredWidth(40);
        tabelClienti.getColumnModel().getColumn(6).setPreferredWidth(200);
        jScrollPane2.setViewportView(tabelClienti);

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/search_icon.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(1, 198, 83));

        Nume.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Nume.setForeground(new java.awt.Color(230, 230, 230));
        Nume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nume.setText("Welcome Nume_Angajat");

        addClient.setBackground(new java.awt.Color(255, 255, 255));
        addClient.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addClient.setForeground(new java.awt.Color(51, 51, 51));
        addClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/add.png"))); // NOI18N
        addClient.setText(" Add new client");
        addClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClientMouseClicked(evt);
            }
        });

        levelLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        levelLabel.setForeground(new java.awt.Color(230, 230, 230));
        levelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelLabel.setText("employee level ");

        accessLoanForm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        accessLoanForm.setForeground(new java.awt.Color(51, 51, 51));
        accessLoanForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accessLoanForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking_app/loan.png"))); // NOI18N
        accessLoanForm.setText("Loan Form");
        accessLoanForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        accessLoanForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accessLoanForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accessLoanFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addClient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(accessLoanForm, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Nume)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClient, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelLabel)
                    .addComponent(accessLoanForm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Nume.getAccessibleContext().setAccessibleName("JLabel1");

        attribute.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        attribute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Last Name", "Surname", "Email", "Phone Number" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(Transactions, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attribute, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(attribute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Transactions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        login.setVisible(true);
        nivel = 0;
        employeeEmail = "";
        
    }//GEN-LAST:event_ExitActionPerformed

    private void TransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsActionPerformed
        trans.setVisible(true);
        this.setFocusableWindowState(false);
        
        String SelectedEmail = tabelClienti.getValueAt(tabelClienti.getSelectedRow(), 2).toString();
        
        String lines[] = handler.RetrieveTransactions(SelectedEmail).split("\\r?\\n");
        trans.addTransactions(lines);
        
    }//GEN-LAST:event_TransactionsActionPerformed

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        if (evt.getKeyChar() == '\n') {
            try {
                Search(searchField.getText());
            } catch (JSONException ex) {
            }
        }
    }//GEN-LAST:event_searchFieldKeyTyped

    private void addClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientMouseClicked
        ClientForm.setVisible(true);
        this.setFocusableWindowState(false);
    }//GEN-LAST:event_addClientMouseClicked

    private void accessLoanFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accessLoanFormMouseClicked
        if (!tabelClienti.getSelectionModel().isSelectionEmpty()) {
            loanForm.setEmail(tabelClienti.getValueAt(tabelClienti.getSelectedRow(), 2).toString(), this.employeeEmail);
            loanForm.setClientName("<html><u>Requesting client name</u>:  "
                    + tabelClienti.getValueAt(tabelClienti.getSelectedRow(), 0).toString() + " " 
                    + tabelClienti.getValueAt(tabelClienti.getSelectedRow(), 1).toString()
                    + "</html>");
            
            loanForm.setVisible(true);
            this.setFocusableWindowState(false);
        } else {
            errorWindow("No client selected!");
        }
    }//GEN-LAST:event_accessLoanFormMouseClicked
    
    private void initTable() throws JSONException{
        entriesJSON = handler.Retrieve("clienti");
        model = (DefaultTableModel) tabelClienti.getModel();
        model.setRowCount(0);
        
        for(int i = 0; i < entriesJSON.size(); i++)
            model.addRow(new Object[]
                            {
                             entriesJSON.get(i).getString("nume"), 
                             entriesJSON.get(i).getString("prenume"),
                             entriesJSON.get(i).getString("email"), 
                             entriesJSON.get(i).getString("telefon"),
                             Float.parseFloat(entriesJSON.get(i).getString("soldCurent")), 
                             (entriesJSON.get(i).getString("creditActiv").equals("da")),
                             entriesJSON.get(i).getString("iban")
                            }
                        );
    
        
    }
    
    private void Search(String text) throws JSONException{
        entriesJSON = handler.Retrieve("clienti");
        String selectie = "nume";
        model = (DefaultTableModel) tabelClienti.getModel();
        model.setRowCount(0);

        switch (attribute.getSelectedItem().toString()) {
            case "Last Name":
                selectie = "nume";
                break;
                
            case "Surname":
                selectie = "prenume";
                break;

            case "Email":
                selectie = "email";
                break;
                
            case "Phone Number":
                selectie = "telefon";
                break;
        }


        for (int i = 0; i < entriesJSON.size(); i++) {
            if (entriesJSON.get(i).getString(selectie).toLowerCase().contains(text.toLowerCase())) {
                model.addRow(new Object[]{
                    entriesJSON.get(i).getString("nume"),
                    entriesJSON.get(i).getString("prenume"),
                    entriesJSON.get(i).getString("email"),
                    entriesJSON.get(i).getString("telefon"),
                    Float.parseFloat(entriesJSON.get(i).getString("soldCurent")),
                    (entriesJSON.get(i).getString("creditActiv").equals("da")),
                    entriesJSON.get(i).getString("iban")
                }
                );
            }
        }
    }

    private void errorWindow(String message){
        JLabel label = new JLabel(message);
        label.setFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 19));
        JOptionPane.showMessageDialog(null, label, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void setNume(String name) {
        Nume.setText(name);
    }
    
    public void setEmail(String email){
        employeeEmail = email;
    }
    
    public String getEmail(){
        return this.employeeEmail;
    }
    
    public void setNivelAngajat(int lvl){
        nivel = lvl;
    }
    
    public int getNivelAngajat(){
        return nivel;
    }
    
    public void setNivelLabel(String level){
        levelLabel.setText(level);
    }
    
    
    public void setLoginTransForms(Login log, Transactions tran, AddClientForm add, LoanApplicationForm lf) {
        this.login = log;
        this.trans = tran;
        this.ClientForm = add;
        this.loanForm = lf;
    }
    

    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Nume;
    private javax.swing.JButton Transactions;
    private javax.swing.JLabel accessLoanForm;
    private javax.swing.JLabel addClient;
    private javax.swing.JComboBox<String> attribute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable tabelClienti;
    // End of variables declaration//GEN-END:variables
}
